Translation of Cloud Native Security White Paper(Chinese) #470
cncf/sig-security pull request #471
Opened 2020-11-29 10:43 UTC by babysor

According to proposal #470 ,  we conducted a Chinese translation and review of Cloud Native Security White Paper. Thanks to the amazing teamwork and Jimmy's initiating.

2020-11-29 13:14 UTC, rootsongjc commented on security-whitepaper/cloud-native-security-whitepaper-simple-chinese.md
> +# **执行摘要**
标题里的加粗格式可以去掉。

2020-11-29 13:15 UTC, rootsongjc commented on security-whitepaper/cloud-native-security-whitepaper-simple-chinese.md
> +![img](https://docimg3.docs.qq.com/image/HrNJkDYdc9qke6Cgq6wEGg?w=1223&h=591)
图片应该是使用 GitHub 里的相对链接。

2020-11-29 13:25 UTC, rootsongjc commented on security-whitepaper/cloud-native-security-whitepaper-simple-chinese.md
> +●   识别可能危及系统的安全上下文和系统调用；
列表格式需要调整。

2020-11-30 10:05 UTC, Gsealy commented
@rootsongjc @babysor 
about ***Encryption*** part, I have retranslate it try to read more fluently.
PTAL

```markdown
#### 加密

对容器镜像进行加密，从而保证镜像内容的机密性。加密后，以确保它们从构建到运行前都是密文态。当加密镜像分发后受到破解，制品库中存储的镜像仍然是加密的，这有助于保护商业机密或其他保密材料等。

容器镜像加密的另一个常见用途是容器镜像授权的增强。当镜像加密与密钥证明管理和/或授权、认证发布等相结合时，可以要求容器镜像只能在特定平台上运行。容器镜像授权也适合保证合规性，例如地理限制、出口管控和数字版权媒体管理。
```

2020-11-30 12:03 UTC, rootsongjc commented
> @rootsongjc @babysor
> about _**Encryption**_ part, I have retranslate it try to read more fluently.
> PTAL
> 
> ```gfm
> #### 加密
> 
> 对容器镜像进行加密，从而保证镜像内容的机密性。加密后，以确保它们从构建到运行前都是密文态。当加密镜像分发后受到破解，制品库中存储的镜像仍然是加密的，这有助于保护商业机密或其他保密材料等。
> 
> 容器镜像加密的另一个常见用途是容器镜像授权的增强。当镜像加密与密钥证明管理和/或授权、认证发布等相结合时，可以要求容器镜像只能在特定平台上运行。容器镜像授权也适合保证合规性，例如地理限制、出口管控和数字版权媒体管理。
> ```

可以使用这个翻译替换下。

2020-11-30 17:51 UTC, lumjjb commented
Thanks @babysor , @rootsongjc, @Gsealy! This is really great! I think that if there is a consensus among the 3 of you that it is good, then we can go ahead and approve this.

I would add a couple asks:
- Can we add a link to the version that is being translated. Want to make sure that we keep that information in case we need to make edits to the whitepaper that need to be propagated. We can link to a commit ID of the github repo.
- For the authors, seems like there's a mix, I think let's keep it all the same or add brackets for translation of names.

2020-12-02 08:58 UTC, hbrls commented on security-whitepaper/cloud-native-security-whitepaper-simple-chinese.md
> +随着技术的进步，我们所处的网络环境正日益复杂，安全风险也不断升级。传统基于边界的安全防护机制，如防火墙等，在云大物移的场景下很难面面俱到。因此，如果只关注云原生带来的开发和部署的敏捷性，我们或将直面安全风险。为更好保护我们的应用，我们需要一些新的安全方法，更接近于基于元数据或属性来识别动态工作负载（如 SDP 软件定义边界提供了一种实现思路）。这类方法可以更细粒度的识别和保护工作负载，以满足云原
云大物移 -> 云原生

2020-12-02 09:04 UTC, hbrls commented on security-whitepaper/cloud-native-security-whitepaper-simple-chinese.md
> +云原生开发可以采用不同的方式来建模，来构成应用开发的生命周期，研发、分发、部署、运行态是其中比不可少的要素之一。云原生安全与传统安全方法的最大不同在于，云原生安全需要有一种强有力的机制，更柔和的嵌入方式，来确保安全措施在不同的环节中有效实施。而不能像传统安全方法一样在应用开发生命周期的末尾，通过分散且粗暴的方式进行干预管理。
比不可少 -> 必不可少

2020-12-02 09:48 UTC, hbrls commented on security-whitepaper/cloud-native-security-whitepaper-simple-chinese.md
> +容器和微服务架构的采用和革新带来了不少挑战。在现代化组织中，减少网络安全漏洞的需求优先级已经成明显趋势地攀升。同时，随着围绕云应用的创新加速，新的威胁状况也在增加。安全领导层需要通过采取预防、检测和应对网络威胁等措施、满足严格的合规要求，来完成他们身上背负的“保护包括人力 [4] 和非人力资产”任务。然而，有个常见的旧说法，指责这些安全措施阻碍了 DevOps 团队的速度和敏捷性。因此，安全领导
安全领导层 -> 安全行业领袖

2020-12-02 10:06 UTC, hbrls commented on security-whitepaper/cloud-native-security-whitepaper-simple-chinese.md
> +FaaS（函数即服务， Functions-as-a-Service ) 是另一种云原生部署模式，是一种允许企业用户通过可执行代码来响应事件的云服务，这种模式用户无需构建和启动微服务相关的复杂基础设施。在云端托管一个软件应用，通常需要配置和管理一个虚拟环境，管理操作系统和网络组件等。通过 FaaS，物理硬件、虚拟机操作系统和 Web 服务器软件管理都由云服务提供商自动处理。从而使用户能够专注于微
这里不需要空格

2020-12-02 10:48 UTC, hbrls commented on security-whitepaper/cloud-native-security-whitepaper-simple-chinese.md
> +应用程序清单描述了部署容器化应用程序所需的配置。 如基准部分中所述，指南和建议（例如 NIST 800-190 出版物）建议了最佳实践安全实践和应用程序容器的配置。 因此，在 CI/CD 工作流中使用工具来扫描这些应用程序清单以识别可能导致不安全部署状态的配置至关重要。
最佳实践安全实践 -> 最佳实践、安全实践

2020-12-02 10:55 UTC, hbrls commented on security-whitepaper/cloud-native-security-whitepaper-simple-chinese.md
> +在构建时对镜像内容进行数字签名，并在使用前对签名数据进行验证，可以保护该镜像数据在构建和运行之间不被篡改，从而确保组件的完整性和来源。首先必需要有流程确认组件是经过审批的。信任确认还包括验证组件是否具有有效的签名。在最简单的情况下，每个组件都可以由一个签名者签名，以表明组件经过了单一的测试和验证过程。然而，软件供应链在大多数情况下比较复杂，创建一个组件依赖于多个验证步骤，因此依赖于实体的信任集团
必需 -> 必须

2020-12-02 12:56 UTC, babysor commented on security-whitepaper/cloud-native-security-whitepaper-simple-chinese.md
> +容器和微服务架构的采用和革新带来了不少挑战。在现代化组织中，减少网络安全漏洞的需求优先级已经成明显趋势地攀升。同时，随着围绕云应用的创新加速，新的威胁状况也在增加。安全领导层需要通过采取预防、检测和应对网络威胁等措施、满足严格的合规要求，来完成他们身上背负的“保护包括人力 [4] 和非人力资产”任务。然而，有个常见的旧说法，指责这些安全措施阻碍了 DevOps 团队的速度和敏捷性。因此，安全领导
这里应该指组织内的安全leaders（例如CSO）吧

2020-12-02 12:57 UTC, babysor commented on security-whitepaper/cloud-native-security-whitepaper-simple-chinese.md
> +在构建时对镜像内容进行数字签名，并在使用前对签名数据进行验证，可以保护该镜像数据在构建和运行之间不被篡改，从而确保组件的完整性和来源。首先必需要有流程确认组件是经过审批的。信任确认还包括验证组件是否具有有效的签名。在最简单的情况下，每个组件都可以由一个签名者签名，以表明组件经过了单一的测试和验证过程。然而，软件供应链在大多数情况下比较复杂，创建一个组件依赖于多个验证步骤，因此依赖于实体的信任集团
Replaced all.

2020-12-03 02:05 UTC, hbrls commented on security-whitepaper/cloud-native-security-whitepaper-simple-chinese.md
> +容器和微服务架构的采用和革新带来了不少挑战。在现代化组织中，减少网络安全漏洞的需求优先级已经成明显趋势地攀升。同时，随着围绕云应用的创新加速，新的威胁状况也在增加。安全领导层需要通过采取预防、检测和应对网络威胁等措施、满足严格的合规要求，来完成他们身上背负的“保护包括人力 [4] 和非人力资产”任务。然而，有个常见的旧说法，指责这些安全措施阻碍了 DevOps 团队的速度和敏捷性。因此，安全领导
啊，我以为是说业界要赶紧发展通用方案，这样企业才愿意跟进

2020-12-07 05:51 UTC, babysor commented on security-whitepaper/cloud-native-security-whitepaper-simple-chinese.md
> +容器和微服务架构的采用和革新带来了不少挑战。在现代化组织中，减少网络安全漏洞的需求优先级已经成明显趋势地攀升。同时，随着围绕云应用的创新加速，新的威胁状况也在增加。安全领导层需要通过采取预防、检测和应对网络威胁等措施、满足严格的合规要求，来完成他们身上背负的“保护包括人力 [4] 和非人力资产”任务。然而，有个常见的旧说法，指责这些安全措施阻碍了 DevOps 团队的速度和敏捷性。因此，安全领导
因为段落的第二句说了 “在现代化的组织中”，我读下来是在这个scope内的，你觉得呢？

2020-12-10 09:35 UTC, hbrls commented on security-whitepaper/cloud-native-security-whitepaper-simplified-chinese.md
> +只要有可能，读者应使用 HSM 技术用加密密钥保护密码学机密算法或信息。如果无法做到这一点，则应使用基于软件的凭据管理器。
上面两段是不是重复了

2020-12-10 09:37 UTC, hbrls commented on security-whitepaper/cloud-native-security-whitepaper-simplified-chinese.md
> +
下面这几段好多重复啊

2020-12-10 12:21 UTC, hbrls commented on security-whitepaper/cloud-native-security-whitepaper-simplified-chinese.md
> +云原生安全强调在应用程序生命周期的早期引入安全工具，安全测试通过尽早识别合规性违规行为和错误配置等安全测试，尽早发现安全问题。具体实现方法就是通过在研发流程中设置安全闸，要求安全问题在流入下一环节前被处置解决。就像处理流水线中的其他问题，如 BugFix、CI Failures 等问题一样，可以尽量缩短问题的修复时间，更好的实现持续改进。
安全测试通过尽早识别合规性违规行为和错误配置等安全测试，
->
通过安全测试尽早识别合规问题和错误配置等，

2020-12-11 10:02 UTC, hbrls requested changes

2021-01-04 15:23 UTC, tao12345666333 commented on security-whitepaper/cloud-native-security-whitepaper-simplified-chinese.md
> +由于使用的开放源码组件往往是从公共来源中提取的。各组织应在其流水线中，创建不同阶段的仓库。只有已授权的开发人员才能访问公共仓库和拉动基础镜像，然后将其存储在内部仓库中，以便在组织内部广泛使用。此外，还建议有单独的私有仓库，用于保存每个团队或小组的开发工件，最后还有一个暂存或预生产仓库，用于准备生产的镜像。这样可以对开源组件的来源和安全性进行更严格的控制，同时可以对 CI/CD 的各个阶段进行不同
s/拉动/拉取

这样比较符合习惯吧

2021-02-26 16:11 UTC, lumjjb approved these changes
LGTM! This looks really good and looking forward to sharing this with the rest of the community! 
Big thank you to everyone! @rootsongjc, @N3erox0, @cafra, @aiaicaow, @hbrls, @losery, @knwng, @babysor, @gtb-togerther, @dwctua

A couple minor things, which can be included in this PR or a separate one:
- Add a link in https://github.com/cncf/sig-security/blob/master/security-whitepaper/README.md for the translation
- Add a reference to the version of the whitepaper used for translation. The current version is 1.1. Can link to the version in the commit  https://github.com/cncf/sig-security/blob/017e77ff380e303d80adb78e60a1f262e80df0e8/security-whitepaper/cloud-native-security-whitepaper.md

2021-02-26 16:51 UTC, ashutosh-narkar approved these changes

2021-02-26 20:21 UTC, merged