Example of what automated PR doc checking could look like
cncf/sig-security pull request #472
Opened 2020-12-03 02:16 UTC by JohnHillegass

For #311. I'd like to have a quick, smaller group zoom discussion on how we could implement this well if anyone is open to it.

2020-12-08 15:40 UTC, lumjjb commented
This is awesome @JohnHillegass!! Thanks so much, is it easy to create a Makefile command or something that can be used to test locally?

2020-12-08 15:45 UTC, JohnHillegass commented
Oh yes, a make command works for me. I was not sure what the appetite would be for running locally, needing node dependencies and what not. I think we can just communicate install steps though.

2020-12-08 16:10 UTC, lumjjb commented
Yea - I think at least initially it would be super helpful since there's
likely going to be a LOT of cleanup :). Once we have something we can
probably create a containerized version, that would work nicely as well!

On Tue, Dec 8, 2020 at 10:46 AM John Hillegass <notifications@github.com>
wrote:

> Oh yes, a make command works for me. I was not sure what the appetite
> would be for running locally, needing node dependencies and what not. I
> think we can just communicate install steps though.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/cncf/sig-security/pull/472#issuecomment-740700575>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAXLDBWR74FTJZO7CNQHFZ3STZC3RANCNFSM4ULKKPHQ>
> .
>

2020-12-09 18:09 UTC, JonZeolla commented on cspell.json
> +        "HIPPA",
```suggestion
        "HIPAA",
```

2020-12-09 18:11 UTC, JonZeolla commented on CONTRIBUTING.md
> +   blehblel *
```suggestion
```

2020-12-09 18:35 UTC, JonZeolla commented
> Oh yes, a make command works for me. I was not sure what the appetite would be for running locally, needing node dependencies and what not. I think we can just communicate install steps though.

We should be able to have the make rule run a container and volume mount `$(pwd)` into it to reduce host dependencies and enforce version pinning.

2020-12-09 19:28 UTC, JonZeolla requested changes
Please consider https://github.com/JohnHillegass/sig-security/pull/2

2020-12-09 20:02 UTC, JohnHillegass commented
Great points @JonZeolla. Thanks for adding these changes.

2020-12-14 15:53 UTC, lumjjb commented
@JohnHillegass @JonZeolla Do ping here if you think its ready for us to try out! And let's take it out of draft and start reviewing so we can get this awesome feature in!

2020-12-14 22:43 UTC, JohnHillegass commented
@lumjjb I think it's ready to go now! @JonZeolla's refactor makes it very easy to run both locally and remotely with Make and docker-compose.

2020-12-23 18:38 UTC, JohnHillegass commented
@achetal01 thanks for the suggestion today for updating this with a summary. I have added some more details to the first comment in the PR.

2020-12-23 18:45 UTC, JohnHillegass commented
superseded by #497

2020-12-23 18:45 UTC, closed without merging