Update README.md
cncf/sig-security pull request #504
Opened 2021-01-13 18:37 UTC by magnologan

Add reference to SUNSPOT - https://www.crowdstrike.com/blog/sunspot-malware-technical-analysis/

Slack discussion: https://cloud-native.slack.com/archives/CDJ7MLT8S/p1610478830312800

2021-01-13 21:27 UTC, lumjjb commented
It looks like they are referencing the same page, can we have this link be under another link instead of a distinct row, unless i'm missing something here. 

`
[1](https://www.fireeye.com/blog/threat-research/2020/12/evasive-attacker-leverages-solarwinds-supply-chain-compromises-with-sunburst-backdoor.html),[2](https://msrc-blog.microsoft.com/2020/12/13/customer-guidance-on-recent-nation-state-cyber-attacks/),[3](New link)`

2021-01-13 23:14 UTC, magnologan commented
It's kind of a different payload, that's why they called it differently. It is related to SolarWinds but another variant. But no problem, I'll keep them on the same row.

2021-01-14 20:02 UTC, TheFoxAtWork requested changes
Need to remain consistent with the naming schema for supply chain attacks

2021-01-14 20:02 UTC, TheFoxAtWork commented on supply-chain-security/compromises/README.md
> +| [SUNSPOT/Solarigate](2020/solarwinds.md) | 2020 | Malware | [1](https://www.crowdstrike.com/blog/sunspot-malware-technical-analysis/) |
```suggestion
| [SUNSPOT/Solarigate](2020/solarwinds.md) | 2020 | Publishing Infrastructure | [1](https://www.crowdstrike.com/blog/sunspot-malware-technical-analysis/) |
```

2021-01-14 22:42 UTC, closed without merging