Update SUNBURST/Solarigate compromise
cncf/sig-security pull request #505
Opened 2021-01-14 15:02 UTC by joshuagl

Update the SUNBURST/Solarigate compromise base on the details from the
CrowdStrike blog on compromsing the publishing infrastructure with SUNSPOT

Signed-off-by: Joshua Lock <jlock@vmware.com>

2021-01-14 20:04 UTC, TheFoxAtWork commented on supply-chain-security/compromises/README.md
> +| [SUNBURST/Solarigate](2020/solarwinds.md) | 2020 | Publishing Infrastructure/Dev Tooling | [1](https://www.fireeye.com/blog/threat-research/2020/12/evasive-attacker-leverages-solarwinds-supply-chai
```suggestion
| [SUNBURST/Solarigate](2020/solarwinds.md) | 2020 | Publishing Infrastructure | [1](https://www.fireeye.com/blog/threat-research/2020/12/evasive-attacker-leverages-solarwinds-supply-chain-compromises-with-sunburst-backdoor.html), [2](https://msrc-blog.microsoft.com/2020/12/13/customer-guidance-on-recent-nation-state-cyber-attacks/), [3](https://www.crowdstrike.com/blog/sunspot-malware-technical-analysis/) |
```

2021-01-14 20:05 UTC, TheFoxAtWork requested changes
CC @magnologan I think this is is purely publishing infrastructure as the injection occurred right before build.

2021-01-14 22:17 UTC, joshuagl commented
> CC @magnologan I think this is is purely publishing infrastructure as the injection occurred right before build.

Agreed. I've force pushed an update to the README and taken the opportunity to improve the commit message a bit.

2021-01-14 22:24 UTC, magnologan commented
Kk, got it! LGTM.

2021-01-19 16:03 UTC, joshuagl commented
Rebased after the merge of #507.

2021-01-22 17:45 UTC, TheFoxAtWork approved these changes

2021-01-22 17:46 UTC, merged