Document the "event-stream" npm package exploit
cncf/sig-security pull request #516
Opened 2021-01-26 13:27 UTC by MVrachev

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

2021-01-26 13:34 UTC, lumjjb requested changes
Thanks @MVrachev ! Couple of requested changes, if not, LGTM!

2021-01-26 13:34 UTC, lumjjb commented on supply-chain-security/compromises/README.md
> +| [The event-stream vulnerability](2018/event-stream.md) | 2020 | Malicious Maintainer | [1]((https://medium.com/intrinsic/compromised-npm-package-event-stream-d47d08605502)),[2](https://github.com/d
2018?

2021-01-26 13:34 UTC, lumjjb commented on supply-chain-security/compromises/2018/event_stream.md
> +IT contained a fairly simple `index.js` file, as well as a minified `index.min.js` file.
nit: IT -> it

2021-01-26 13:34 UTC, lumjjb commented on supply-chain-security/compromises/2018/event_stream.md
> +3. Send it to a server in Kuala Lumpur (hosted here: https://www.shinjiru.com.my/) and most likely controlled by the attacker.
maybe let's remove the link to the malicious server here :)

2021-01-26 13:53 UTC, MVrachev commented
@lumjjb addressed your comments.

2021-01-26 16:13 UTC, sublimino commented on supply-chain-security/compromises/2018/event_stream.md
> +3. Send it to a server in Kuala Lumpur and most likely controlled by the attacker.
Some extra detail here:

1. Decrypt and execute a hidden AES-encrypted payload using the `package.json` description as a key
1. Search the victim device for "hot wallet" cryptocurrency profiles (this could have been running in mobile apps as well as your regular browser, regardless of the device)
1. Iterate over any crypto wallet IDs to check wallet balances and retrieve private keys
1. For wallets with significant Bitcoin or Bitcoin Cash balances, send the private keys and account data to a server in Kuala Lumpur that was likely controlled by the attacker

2021-01-27 10:16 UTC, MVrachev commented
Updated my pr adding the additional details proposed by @sublimino.
Also changed the long lines in the document in order to comply with the [CONTRIBUTING.md](https://github.com/cncf/sig-security/blob/master/CONTRIBUTING.md) rеquirmenent lines to be 80 characters long.

2021-01-27 14:56 UTC, TheFoxAtWork commented on supply-chain-security/compromises/2018/event_stream.md
> +the `event-stream` package and eventually on he/she gain the trust of the
```suggestion
the `event-stream` package and eventuallysgained the trust of the
```

2021-01-27 14:57 UTC, TheFoxAtWork commented on supply-chain-security/compromises/2018/event_stream.md
> +to him/her.
```suggestion
to "right9ctrl".
```

2021-01-27 14:57 UTC, TheFoxAtWork commented on supply-chain-security/compromises/2018/event_stream.md
> +`index.min.js` file.The two files on GitHub appear innocent enough.
```suggestion
`index.min.js` file.  The two files on GitHub appear innocent enough.
```

2021-01-27 14:59 UTC, TheFoxAtWork requested changes
Made some small suggestions to remove gendering in the write-up.

2021-01-27 16:02 UTC, MVrachev commented
> Made some small suggestions to remove gendering in the write-up.

Updated the pr with those suggestions.

2021-01-27 16:19 UTC, TheFoxAtWork approved these changes
LGTM!!

2021-01-27 16:37 UTC, lumjjb approved these changes
LGTM!

2021-01-27 16:40 UTC, merged