Add VSCode GitHub vulnerability to the list Supply Chain Compromises
cncf/sig-security pull request #525
Opened 2021-02-02 18:04 UTC by magnologan

Reference: https://www.bleepingcomputer.com/news/security/heres-how-a-researcher-broke-into-microsoft-vs-codes-github/

2021-02-03 13:24 UTC, TheFoxAtWork requested changes
@magnologan just one small change

2021-02-03 13:24 UTC, TheFoxAtWork commented on supply-chain-security/compromises/2021/vscode.md
> +Supply Chain Attack: "obtain push access, and write to the repository."
```suggestion
Dev tooling: "obtain push access, and write to the repository."  Source code repositories are considered part of the developer tooling.
```

2021-02-03 13:30 UTC, magnologan commented
Changes accepted.

2021-02-04 00:57 UTC, TheFoxAtWork approved these changes
LGTM

2021-02-04 00:57 UTC, merged