Update APAC frequency to bi-weekly
cncf/sig-security pull request #529
Opened 2021-02-04 06:18 UTC by 0x646e78

Have also added a link to the CNCF calendar for people to be able to check the date of the biweekly meeting.

2021-02-04 13:13 UTC, TheFoxAtWork commented on README.md
> +The Security SIG group meets regularly.
```suggestion
The Security SIG group meets at least weekly.
```

2021-02-04 13:13 UTC, TheFoxAtWork requested changes
one small change.  otherwise LGTM!

2021-02-04 14:04 UTC, lumjjb requested changes
minor nit, if not LGTM too

2021-02-04 14:04 UTC, lumjjb commented on README.md
> +* APAC: Bi-weekly on Tuesdays at 13:00pm GMT+11 (see your timezone [here](https://time.is/compare/1300_26_Jan_2021_in_AEDT))
13:00pm -> 1:00pm.

2021-02-04 23:20 UTC, dnx-seek commented on README.md
> +* APAC: Bi-weekly on Tuesdays at 13:00pm GMT+11 (see your timezone [here](https://time.is/compare/1300_26_Jan_2021_in_AEDT))
Yes I totally agree! I will update.

2021-02-07 23:13 UTC, 0x646e78 commented on README.md
> +The Security SIG group meets regularly.
Pushed an update to reflect this.

2021-02-08 13:10 UTC, TheFoxAtWork approved these changes
LGTM

2021-02-10 04:07 UTC, 0x646e78 commented
@lumjjb looks OK now?

2021-02-14 00:40 UTC, ultrasaurus approved these changes
I don’t think “at least weekly” is the right way to say it, since we sometimes cancel on holidays, but I do think this is important to merge so APAC times are correct before next week!

2021-02-14 00:42 UTC, ultrasaurus commented on README.md
> +The Security SIG group meets at least weekly.
```suggestion
Group meeting times are listed below:
```

2021-02-15 14:12 UTC, lumjjb approved these changes
LGTM

2021-02-15 14:12 UTC, merged

2021-02-16 23:06 UTC, pragashj commented
Closing this issue as a result of this merge. https://github.com/cncf/sig-security/issues/312