Update links to usecases which are currently broken
cncf/sig-security pull request #535
Opened 2021-02-16 01:40 UTC by 0x646e78

Links to usecases are currently dead after the merge of #527 

This PR updates links to the new usecase-personas folder. I have chosen to not link directly to the README.md file to align with an idea that multiple usecases could exist in this folder over time.

2021-02-16 15:25 UTC, TheFoxAtWork commented on security-whitepaper/cloud-native-security-whitepaper.md
> +The focus is on security, protection, detection, and auto-response where ever possible. It is not necessarily development tooling alone, but security tooling that integrates transparently into the de
```suggestion
The focus is on security, protection, detection, and auto-response where ever possible. 
It is not necessarily development tooling alone, but security tooling that integrates 
transparently into the development process to enforce security policies where fast 
feedback and most immediate actions to remediate can occur. For specific information
 on cloud native security use cases refer to the [SIG-Security's use cases listing](https://github.com/cncf/sig-security/usecase-personas/).
```

2021-02-16 15:26 UTC, TheFoxAtWork commented on security-whitepaper/cloud-native-security-whitepaper.md
> +The focus is on security, protection, detection, and auto-response where ever possible. It is not necessarily development tooling alone, but security tooling that integrates transparently into the de
updates this to line wrapping for easier reviews

2021-02-16 15:26 UTC, TheFoxAtWork requested changes
Looks good overall, small line wrapping change for readability in reviews.

2021-02-16 22:39 UTC, 0x646e78 commented
Thanks for the update @TheFoxAtWork , have merged this.

2021-02-17 14:46 UTC, TheFoxAtWork approved these changes
LGTM

2021-02-17 14:46 UTC, merged