Update README.md
cncf/sig-security pull request #567
Opened 2021-03-18 12:38 UTC by aspanner

adding Andreas Spanner to the member list

2021-03-18 13:55 UTC, TheFoxAtWork requested changes
small change

2021-03-18 13:55 UTC, TheFoxAtWork commented on README.md
> +* Andreas Spanner ([@aspanner] (https://github.com/aspanner)), Red Hat
```suggestion
* Andreas Spanner ([@aspanner](https://github.com/aspanner)), Red Hat
```

2021-03-18 13:55 UTC, TheFoxAtWork commented on README.md
> +* Andreas Spanner ([@aspanner] (https://github.com/aspanner)), Red Hat
small change to make so the URL works

2021-03-24 01:41 UTC, aspanner commented on README.md
> +* Andreas Spanner ([@aspanner] (https://github.com/aspanner)), Red Hat
done.

2021-03-25 05:25 UTC, anvega approved these changes

2021-03-25 05:27 UTC, merged